<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    //nombre de projet en cours de réalisation
    public function nombreProjetRealisation() {
        $query = $this->_em->createQuery('SELECT count(u) as nombre FROM AppBundle:Project u WHERE u.delivery=0');
        $results = $query->getResult();
        return $results;
    }

    //nombre de projet terminé
    public function nombreProjetLivree() {
        $query = $this->_em->createQuery('SELECT count(u) as nombre FROM AppBundle:Project u WHERE u.delivery=1');
        $results = $query->getResult();
        return $results;
    }

    //nombre de projet type Capex
    public function nombreProjetCapex() {
        $query = $this->_em->createQuery('SELECT count(u) as nombre FROM AppBundle:Project u WHERE u.typeProjet=\'Capex\'');
        $results = $query->getResult();
        return $results;
    }

    public function nombreProjetOpex() {
        $query = $this->_em->createQuery('SELECT count(u) as nombre FROM AppBundle:Project u WHERE u.typeProjet=\'Opex\'');
        $results = $query->getResult();
        return $results;
    }

    public function rechercheTitre($recherche){
        $query = $this->_em->createQuery('SELECT u FROM AppBundle:Project u WHERE u.titre LIKE :recherche')
            ->setParameter('recherche', '%'.$recherche.'%');

        $results = $query->getResult();
        return $results;
    }
}
