<?php

namespace AppBundle\Repository;

/**
 * TimeTrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeTrackingRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombreJourProduction(){
        $query = $this->_em->createQuery('SELECT SUM (u.nbJour) as nombre FROM AppBundle:TimeTracking u');
        $results = $query->getResult();
        return $results;
    }

    public function nombreJourProductionEmployee($employee){
        $query = $this->_em->createQuery('SELECT SUM (u.nbJour) as nombre FROM AppBundle:TimeTracking u WHERE u.idEmployee=$employee');
        $results = $query->getResult();
        return $results;
    }
    public function coutProjet($project){
        $query = $this->_em->createQuery('SELECT SUM(e.cout*u.nbJour) as coutTotal
            FROM AppBundle:TimeTracking u, AppBundle:Employee e
            WHERE u.idEmployee=e.id 
            AND u.idProject='.$project->getId());
        $results = $query->getResult();
        return $results;
    }

    public function coutTotalProjet(){
        $query = $this->_em->createQuery('SELECT SUM (e.cout*u.nbJour) as coutTotal, p as projet
            FROM AppBundle:TimeTracking u,AppBundle:Employee e, AppBundle:Project p
            WHERE u.idEmployee=e.id
            AND u.idProject=p.id
            GROUP BY u.idProject');
        $results = $query->getResult();
        return $results;
    }

    public function classementEmployee(){
        $query = $this->_em->createQuery('SELECT SUM(u.nbJour*e.cout) as total, u as employee
        FROM AppBundle:TimeTracking u, AppBundle:Employee e 
        WHERE u.idEmployee=e.id 
        GROUP BY u.idEmployee
        ORDER BY total DESC');
        $results = $query->getResult();
        return$results;
    }
}
/*SELECT SUM(nbJour*cout) as coutTotal
FROM time_tracking, employee
WHERE time_tracking.id_employee_id=employee.id
AND id_project_id=12*/

/*SELECT project.*, 0 as cout
FROM project
WHERE id NOT IN (SELECT id_project_id
FROM time_tracking)
UNION
SELECT project.*, SUM(cout*nbJour)
FROM time_tracking, project, employee
Where time_tracking.id_employee_id=employee.id
AND time_tracking.id_project_id=project.id
GROUP BY id_project_id
ORDER BY dateCreation DESC*/
